### ISSUE TITLE
Links to Game Dev Website

### ISSUE THREAD

**Issue by rakhadjo** [unicsmcr/unicsmcr-2021#1]
Can you add a Link on the header that redirects to the Game Dev Website [https://gamedev.unicsmcr.com](https://gamedev.unicsmcr.com) on the navbar

**Comment by ary4n99** [comment]
I've added a text link in the navbar, but I've also commented out an image link next to the "Join Us"  button. 
Which do you prefer? 

![2021-07-30 23_21_27-UniCS](https://user-images.githubusercontent.com/57862028/127712944-e58e5402-bd51-4fde-bf46-ca927eea8511.png)
![2021-07-30 23_22_42-UniCS](https://user-images.githubusercontent.com/57862028/127712946-93570780-b95d-46ad-a284-2a33068e3781.png)
